FROM python:3.10-alpine

ARG UID=1000
ARG GID=1000

WORKDIR /app

# Install build tools
RUN apk add --no-cache build-base

# Create group and user
RUN addgroup -g ${GID} bishal \
 && adduser -D -u ${UID} -G bishal bishal

# Set ownership
RUN chown -R bishal:bishal /app

# Copy files with correct ownership
COPY --chown=bishal:bishal . /app

RUN pip install -r requirements.txt --no-cache-dir

# Switch to non-root user
USER bishal

EXPOSE 3000

CMD ["gunicorn", "-b", "0.0.0.0:3000", "hello:app"]